name: AIChatBot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip>=23.3
  - flask=3.0.0
  - flask-cors=4.0.0
  - flask-restful=0.3.10
  - google-auth-oauthlib=1.1.0
  - importlib-metadata=6.8.0
  - langchain=0.0.329
  - openai=0.28.1
  - openapi-schema-pydantic=1.2.4
  - openpyxl=3.1.2
  - pandas=2.1.2
  - pandas-stubs=2.1.1.230928
  - plotly=5.18.0
  - pyopenssl=23.3.0
  - pysocks=1.7.1
  - python-dotenv=0.21.0
  - pytube=15.0.0
  - pyu2f=0.1.5
  - scikit-learn=1.3.2
  - textblob=0.15.3
  - unicodedata2=15.1.0
  - pip:
      - firebase-admin==6.2.0
      - protobuf==4.25.0
      - grpcio-status==1.59.2
      - openai-whisper==20230918
      - chromadb==0.4.15
      - unstructured==0.10.28
      - pypdf==3.17.0